spring:
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    mallProduct:
      path: /productApi/**
      serviceId: mall-product
    mallUser:
      path: /userApi/**
      serviceId: mall-user
    mallOrder:
      path: /orderApi/**
      serviceId: mall-order
