eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: mall-order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
      url: jdbc:mysql://127.0.0.1/mall_order?characterEncoding=utf-8&useSSL=false
  zipkin:
        base-url: http://localhost:9000
  jpa:
     show-sql: true
