eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: mall-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amanxu/mall-config-repo.git
          username: amanxu@126.com
          password: nm198721
